# Generated by Django 4.1.6 on 2023-02-27 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_teacher_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='skills',
            field=models.CharField(max_length=100),
        ),
    ]
