# Generated by Django 4.1.6 on 2023-02-27 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_course_description_alter_course_techs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='techs',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='coursecategory',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='interested_categories',
            field=models.TextField(null=True),
        ),
    ]
